{"name": "test_wrong_login", "status": "passed", "description": "\"test_wrong_login\" is the test that try auth with wrong login", "steps": [{"name": "authorization wrong login", "status": "passed", "start": 1694881183348, "stop": 1694881191526}], "attachments": [{"name": "stdout", "source": "7591fb88-9a6f-4cc6-9156-55c12b86b4d4-attachment.txt", "type": "text/plain"}], "start": 1694881176827, "stop": 1694881191673, "uuid": "72eff62c-77d6-4b6f-babc-78da05629947", "historyId": "895cdcf3adb0628e34b928aea7619ec2", "testCaseId": "895cdcf3adb0628e34b928aea7619ec2", "fullName": "tests.test_authorizations#test_wrong_login", "labels": [{"name": "tag", "value": "order(1)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorizations"}, {"name": "host", "value": "MacBook-Air-Aleksej.local"}, {"name": "thread", "value": "20432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorizations"}]}